baseURL = 'https://scottlabram.uk'
languageCode = 'en-us'
title = 'Scott Labram'
theme = "puppet"

[params]
description = "Hello and welcome to my website. I am a 17 year old who is an aspiring pyro and lighting technician. I am currently learning how to use ETC's EOS systems and hope to lean MagicQ and MA2/3. I use depence r3 and am trying to learn how to make firework/pyro visualisations in Unreal Engine 5.3."

[markup.goldmark.renderer]
unsafe = true

[params.social.instagram]
weight = 56
icon = "fab fa-instagram"
format = "https://www.instagram.com/%v"
id = "scott.labram"
url = "https://www.instagram.com/scott.labram"

[params.social.facebook]
weight = 56
id = "scottlabram"
url = "https://www.facebook.com/scottlabram"
format = "https://facebook.com/%v"
icon = "fab fa-facebook"

[params.social.linkedin]
weight = 56
id = "scott-labram"
format = "https://linkedin.com/in/%v"
url = "https://www.linkedin.com/in/scott-labram"
icon = "fab fa-linkedin"

[params.social.whatsapp]
weight = 99
format = "https://wa.me/%v"
id = "07415113573"
url = "https://wa.me/07415113573"
icon = "fab fa-whatsapp"

[params.social.email]
weight = 1
format = "mailto:%v"
icon = "far fa-envelope"
id = "scottdlabram@gmail.com"

[[menu.main]]
name = 'Home'
pageref = '/'
weight = 1

[[menu.main]]
name = 'Portfolio'
pageref = '/portfolio'
weight = 2

[[menu.main]]
name = 'Contact'
pageref = '/contact'
weight = 3

[[menu.main]]
name = 'Gallery'
pageref = '/gallery'
weight = 4

[params.sidebar]
enable = false
